name: Build Report

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run audit
        run: python scripts/run_audit.py
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: data/report.json
